---
title: "Oregon Wine at a Glance"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

<style>
blockquote {
  background: #f9f9f9;
  border-left: 5px solid #ccc;
  margin: 1.5em 10px;
  padding: 0.5em 1.5em;
}

strong{
  color: #018080;
}

A{
  color: #018080;
}

</style>

```{r setup, include=FALSE}
library(flexdashboard)
setwd("~/GDrive/teaching/GSMDS-5001/")
library(tidyverse)
library(moderndive)
wine <- read_csv("resources/winemag-data.csv") %>% 
  filter(!is.na(price)) %>%
  mutate(year = as.numeric(str_extract(title,"(\\d{4})"))) %>% 
  filter(province == "Oregon") %>% 
  filter(variety %in% c("Pinot Noir", "Cabernet Sauvignon", "Syrah"))
  
jameson <- theme_minimal() +
    theme(
      text = element_text(family = "Palatino", color = "gray25"),
      plot.subtitle = element_text(size = 12),
      plot.caption = element_text(color = "gray30"),
      plot.background = element_rect(fill = "gray95"),
      plot.margin = unit(c(5, 10, 5, 10), units = "mm")
    )
theme_set(jameson)

library(wesanderson)
scale_colour_discrete <- function(...) {
  scale_colour_manual(..., values = wes_palette(n=8, name="Moonrise3", type = "continuous"))
}
scale_fill_discrete <- function(...) {
  scale_fill_manual(..., values = wes_palette(n=8, name="Moonrise3", type = "continuous"))
}

lc=wes_palette(n=2, name="Moonrise3")[[1]]
hc=wes_palette(n=2, name="Moonrise3")[[2]]
scale_colour_continuous <- function(...) {
  scale_colour_gradient(..., low = lc, high = hc)
}
scale_fill_continuous <- function(...) {
  scale_fill_gradient(..., low = lc, high = hc)
}
```

Row
-----------------------------------------------------------------------

### Average Price

```{r}
avg_price <- wine %>% summarize(price=mean(price))
gauge(round(avg_price$price), min = 0, max = 100, 
      gaugeSectors(success = c(80, 100), warning = c(40, 79), danger = c(0, 39)))
```

### Average Points

```{r}
avg_points <- wine %>% summarize(points=mean(points))
gauge(round(avg_points$points), min = 0, max = 100, 
      gaugeSectors(success = c(80, 100), warning = c(40, 79), danger = c(0, 39)))
```

### Choices

```{r}
choices <- wine %>% count()
valueBox(choices, icon = "fa-comments")
```

Row {data-height=300}
-----------------------------------------------------------------------


### Chart A

```{r}
wine %>% 
  ggplot(aes(points, fill=variety))+
  geom_density()+
  facet_grid(. ~variety)
```


### Chart B

```{r}
wine %>%
  filter(province %in% c("Washington","Oregon","California")) %>% 
  filter(variety %in% c("Pinot Noir", "Cabernet Sauvignon", "Syrah")) %>% 
  ggplot(aes(points, log(price), color=variety))+
  geom_density_2d()+
  facet_grid(. ~ variety)+
  theme(legend.position="none")
```

### Chart C

```{r}
wine %>% 
  ggplot(aes(points,log(price)))+
  geom_bin2d(bins=20)+
  facet_grid(. ~ variety)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Average points over time
```{r, fig.width=15}
wine %>% 
  filter(year < 2015 & year > 1999) %>% 
  group_by(year) %>% 
  summarise(points=mean(points)) %>% 
  ggplot(aes(x = year, y = points))+
  geom_line()
```

### Average price over time
```{r, fig.width=15}
wine %>% 
  filter(year < 2015 & year > 1999) %>% 
  group_by(year) %>% 
  summarise(price=mean(price)) %>% 
  ggplot(aes(x = year, y = price))+
  geom_line()
```

